from artificial_bee_colony.goals.adaptive_fuzzy_clustering import AdaptiveFuzzyClustering
from artificial_bee_colony.goals.clustering import Clustering
from artificial_bee_colony.goals.fuzzy_clustering import FuzzyClustering, FuzzyClusteringNeighbors, FuzzyClusteringWithCenters
from artificial_bee_colony.goals.multi_fuzzy_clustering import MultiFuzzyClustering
from artificial_bee_colony.goals.meaning_of_life import MeaningOfLife, MeaningsOfLife
from artificial_bee_colony.goals.modified_fuzzy_clustering import ModFuzzyClustering, DEFuzzyClustering, FastExploreFuzzyClustering
from artificial_bee_colony.goals.gl_fuzzy_clustering import GLFuzzyClustering
